// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"276e3779fc9493d6e0df315198be9c2e7adbc024d1fa0407f0953aab688039c6d45e56004bd73847d1ad437e721529acc356a7ce03b50d4a1480259660cff601"}}
];
